spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karnan131k/spring-cloud-config-store.git
          default-label: master
          search-paths:
          - '*service'

